### insert book
POST {{base}}
content-type: application/json

{
  "name": "The Lord Of The Rings Illustrated Edition",
  "meta": {
    "isbn10": "0358653037",
    "isbn13": "978-0358653035",
    "subTitle": "Illustrated Edition",
    "seriesInformation": "Load of The Rings",
    "author": "J.R.R. Tolkien",
    "contributors": "",
    "publisher": "William Morrow; Illustrated edition (November 16, 2021)",
    "keywords": "Load of The Rings,Illustrated Edition"
  }
}

### insert book 1
POST {{base}}
content-type: application/json

{
  "name": "The Fellowship Of The Ring: Being the First Part of The Lord of the Rings (The Lord of the Rings, 1)",
  "meta": {
    "isbn10": "0395489318",
    "isbn13": "978-0395489314",
    "subTitle": "Being the First Part of The Lord of the Rings (The Lord of the Rings, 1)",
    "seriesInformation": "Load of The Rings",
    "author": "J.R.R. Tolkien",
    "contributors": "",
    "publisher": "William Morrow; Subsequent,Reissue edition (March 3, 1988)",
    "keywords": "Load of The Rings,Being the First Part of The Lord of the Rings"
  }
}

### find by name
GET {{base}}?name=Of%20The%20Ring

### find by id & convert to VO
GET {{base}}/1/toVO


### find by name & paging
GET {{base}}/paging?name=Of%20The%20Ring&number=0&size=1


### update book 1
PUT {{base}}
content-type: application/json

{
  "findBookSpec": {
    "name": "Fellowship"
  },
  "name": "ChangedName"
}

### find by name
GET {{base}}?name=ChangedName

### delete by name
DELETE {{base}}
content-type: application/json

{
  "name": "Changed",
  "publisher": "William Morrow; Subsequent,Reissue edition (March 3, 1988)"
}

### find by name
GET {{base}}?name=ChangedName